Finnish locale for staticpages plugin
pkp/staticPages pull request #22
Opened 2017-05-24 11:24 UTC by ajnyga

Hi @mtub 

Fi locale for the plugin...

2017-05-29 20:44 UTC, mtub requested changes
please update according to my comments…

2017-05-29 20:44 UTC, mtub commented on locale/fi_FI/locale.xml
> +  * locale/en_US/locale.xml
locale/fi_FI/locale.xml

2017-05-29 20:44 UTC, mtub commented on locale/fi_FI/locale.xml
> +  * Copyright (c) 2014-2016 Simon Fraser University Library
... 2017

2017-05-29 20:44 UTC, mtub commented on locale/fi_FI/locale.xml
> +  * Copyright (c) 2003-2016 John Willinsky
... -2017

2017-05-30 08:37 UTC, ajnyga commented
check!

2017-05-31 19:10 UTC, merged